### ISSUE TITLE
Support for nuget.conf in .NET Core

### ISSUE THREAD

**Issue by GGG-KILLER** [kubeless/runtimes#45]
I am not sure if I missed a part of the documentation, but I couldn't find in the documentation a way to include a `nuget.conf` file along with the `.csproj` file in a .NET Core function. Is this already supported or is there a way that support for this could be added?

The `nuget.conf` file is used to manage the nuget repositories used for dependency resolution in a solution.

**Comment by allantargino** [comment]
Hi @GGG-KILLER,
This is not currently supported - but we are open to contributions :)

**Comment by GGG-KILLER** [comment]
Hi @allantargino, I'd love to contribute however I'm not sure where or how I could begin.
Do you have any resources or tips on where to get started?

**Comment by GGG-KILLER** [comment]
An update on this: the `nuget.conf` can be included in the function if you upload a `.zip` file (I thought this might work but hadn't confirmed until now).

So I believe that we only need to update the docs to mention this @allantargino.

**Comment by GGG-KILLER** [comment]
Closing as kubeless/kubeless#1072 has been merged.
