### ISSUE TITLE
Binary only package for golang

### ISSUE THREAD

**Issue by aphsa** [kubeless/runtimes#51]
Is there a way to use pre-compiled  package in golang runtime in kubeless?

kubeless function deploy iseven   --from-file iseven.a --handler func.IsEven --runtime go1.12

**Comment by andresmgot** [comment]
Hi @aphsa,

Unfortunately that's not supported. The only option right now to avoid compiling files on the fly is to enable the function builder: https://kubeless.io/docs/building-functions/. With that the golang function will be compiled just once (the first time it gets deployed).
