### ISSUE TITLE
Add a Python 3.8 Runtime?

### ISSUE THREAD

**Issue by danieltahara** [kubeless/runtimes#72]
Would it be possible to include a python 3.8 runtime?

**Comment by andresmgot** [comment]
yes, we just need to replicate the current logic for previous versions. A pull request would be welcomed!

**Comment by vladimirtiukhtin** [comment]
@andresmgot  do you guys use bitnami on purpose? What if I port python runtime to community image?

**Comment by a5r0n** [comment]
anyway, no need to copy-paste Dockerfiles from bitnami..
instead just use them with `FROM bitnami/pythonX.X` 
so we got up-to-date runtime..
(maybe with tag pinning?)

**Comment by andresmgot** [comment]
_Closing this since Python 3.8 is already available as runtime_
