### ISSUE TITLE
Developer guide link to interface appears to be broken

### ISSUE THREAD

**Issue by sshanks-kx** [kubeless/runtimes#79]
In the DEVELOPER_GUIDE.md, there is a section of text that appears to have a broken link

This bit of text ...

"Functions should receive two parameters: event and context and should return the value that will be used as HTTP response. See **the functions standard signature** for more information. The information that will be available in event parameter will be received as HTTP headers."

has a link to https://github.com/kubeless/runtimes/blob/master/docs/runtimes#runtimes-interface which doesn't appear to resolve for me

**Comment by andresmgot** [comment]
where are you reading the docs? Note that the source on GitHub are not meant to be used, those are used as source to generate the docs in kubeless.io. In this case, the link you mention should be pointing to https://kubeless.io/docs/kubeless-functions/#functions-interface
