### ISSUE TITLE
Update PHP Images

### ISSUE THREAD

**Issue by shyim** [kubeless/runtimes#91]
The Images are still PHP 7.3. Already 7.4 is out since one year so far

**Comment by andresmgot** [comment]
what are you looking for @shyim ?

**Comment by shyim** [comment]
The Images are still PHP 7.3 😅

**Comment by andresmgot** [comment]
Got it. Looking for contributions here

**Comment by shyim** [comment]
When it's just updating the docker image. I can go for it. I don't know how complex all these things are working here :D

**Comment by hjanuschka** [comment]
https://github.com/kubeless/runtimes/pull/98
