### ISSUE TITLE
How to require/read files from NodeJS function

### ISSUE THREAD

**Issue by Vallerious** [kubeless/runtimes#96]
Hello!

I have a folder full of html files that are static sites. My nodejs script loads them and runs checks on them for the existence of specific html tags. I use url+zip packaging and my script and the directory in question are on the same file level.
I tried to read the files using
```
let websites = fs.readdirSync("./static-websites-dir")
```
but I get an error:
```
Function failed to execute: fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './static-websites-dir'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/kubeless/scan-websites.js:56:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at modRequire (/kubeless_rt/kubeless.js:62:16)
::ffff:10.200.125.192 - - [15/Sep/2020:07:42:51 +0000] "POST / HTTP/1.1" 500 21 "-" "okhttp/3.12.6"

```

When I ran for debugging:
```
const files = fs.readdirSync('./');
console.log(JSON.stringify(files));
```
I did not see my folder anywhere...
Is there a way to deal with that without creating custom images?

**Comment by andresmgot** [comment]
Are you sure your folder is included in the Zip file? Kubeless just unzips whatever is in the file in the destination folder so you should be able to access it. You can check the commands that are being executed if you get the pod YAML.

**Comment by Vallerious** [comment]
Yes, I am confident about that. The zip contains the files. Actually, I have previously bundled node_modules and a script file that uses a dependency and it worked.
My observations so far lead me to the hypothesis that my folder is not copied into the 'kubeless_rt' folder that gets created.
But as I am writing this, it occurred to me that I can add my custom folder in 'lib' and then it will be copied - I think that kubeless docs mentions that if you want some third-party, non-npm modules you can add them in lib. 
I have to test this first and will update the issue with my findings.

**Comment by Vallerious** [comment]
I managed to get access to the files in the zip by going `../kubeless` in my script folder - `kubeless_rt`, because the two are siblings.
